# Generated by Django 4.1 on 2022-08-15 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название бренда')),
                ('image', models.ImageField(upload_to='brands')),
                ('slug', models.SlugField(max_length=250)),
                ('sale', models.BooleanField(blank=True, default=False, verbose_name='Распродажа у бренда')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Вид питомца')),
                ('img', models.ImageField(blank=True, upload_to='pets/%Y/%m/%d')),
                ('slug', models.SlugField(max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Питомец',
                'verbose_name_plural': 'Питомцы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Тип товара')),
                ('slug', models.SlugField(max_length=250)),
            ],
            options={
                'verbose_name': 'Тип товара',
                'verbose_name_plural': 'Типы товаров',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название товара')),
                ('description', models.TextField(verbose_name='описание')),
                ('slug', models.SlugField(max_length=250)),
                ('key_features', models.TextField(blank=True, verbose_name='ключевые особенности')),
                ('compound', models.TextField(verbose_name='состав')),
                ('guaranteed_analysis', models.TextField(blank=True, verbose_name='гарантированный анализ')),
                ('nutritional_supplements', models.TextField(blank=True, verbose_name='пищевые добавки')),
                ('available', models.BooleanField(verbose_name='доступность')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount', models.BooleanField(blank=True, default=False, verbose_name='Товар на акции')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand', to='main.brand')),
                ('pet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pet', to='main.pet')),
                ('product_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type', to='main.producttype')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['title', '-created'],
            },
        ),
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/%d')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_img', to='main.product')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='product_type',
            field=models.ManyToManyField(related_name='prod_type', to='main.producttype'),
        ),
    ]
