# Generated by Django 4.1 on 2022-08-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_stock_alter_brand_slug_alter_pet_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='sale',
            field=models.BooleanField(blank=True, default=False, verbose_name='Скидка у категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
