# Generated by Django 4.1 on 2022-08-23 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_producttype_sale_alter_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='articles/%Y/%m/%d')),
                ('time_read', models.PositiveIntegerField(verbose_name='Время чтения, мин.')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата опубликования')),
                ('pet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.pet')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-created', 'title'],
            },
        ),
    ]
