# Generated by Django 4.1 on 2022-09-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userip_alter_pet_options_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='amount_of_discount',
            field=models.IntegerField(blank=True, default=0, verbose_name='Размер скидки'),
        ),
        migrations.AlterField(
            model_name='productweight',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, verbose_name='Вес в кг'),
        ),
    ]
