# Generated by Django 4.1 on 2022-09-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_product_stock_product_amount_of_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='views',
        ),
        migrations.AlterField(
            model_name='product',
            name='amount_of_discount',
            field=models.IntegerField(blank=True, default=0, verbose_name='Размер скидки в %'),
        ),
        migrations.DeleteModel(
            name='UserIp',
        ),
    ]
